import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { ScrollContextProvider } from "@/store/contexts/ScrollContext";
import { ThemeProvider } from "@/components/providers/theme-provider";
import AlertsProvider from "@/components/providers/AlertsProvider";
import { Analytics } from "@vercel/analytics/next";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NeuroPost",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ colorScheme: "dark" }} suppressHydrationWarning>
      <body className={`${plusJakartaSans.variable} antialiased`}>
        <Analytics />
        <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem>
          <ScrollContextProvider>
            <ReactQueryProvider>
              <Header />
              <AlertsProvider />
              {children}
              <div className="h-10"></div>
            </ReactQueryProvider>
          </ScrollContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
