#!/bin/sh

set -e

npx lint-staged

FILES=$(git diff --cached --name-only)

if echo "$FILES" | grep -q "^client/"; then
  echo "Checking client changes..."

  npm run typecheck:client
fi

if echo "$FILES" | grep -q "^server/"; then
  echo "Checking server changes..."

  npm run typecheck:server
  npm run test:server:run
fi