name: Server CI

on:
  push:
    branches: [main]
    paths:
      - "server/**"
  pull_request:
    paths:
      - "server/**"

concurrency:
  cancel-in-progress: true
  group: server-ci-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

          
      - name: Install deps
        run: npm ci
          
      - name: Format check
        run: npm run prettier:check

      - name: Type check
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
